// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/runlytics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runlytics_BatchUpdate_FullMethodName = "/runlytics.Runlytics/BatchUpdate"
)

// RunlyticsClient is the client API for Runlytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunlyticsClient interface {
	BatchUpdate(ctx context.Context, in *BatchUpdateRequest, opts ...grpc.CallOption) (*BatchUpdateResponse, error)
}

type runlyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewRunlyticsClient(cc grpc.ClientConnInterface) RunlyticsClient {
	return &runlyticsClient{cc}
}

func (c *runlyticsClient) BatchUpdate(ctx context.Context, in *BatchUpdateRequest, opts ...grpc.CallOption) (*BatchUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateResponse)
	err := c.cc.Invoke(ctx, Runlytics_BatchUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunlyticsServer is the server API for Runlytics service.
// All implementations must embed UnimplementedRunlyticsServer
// for forward compatibility.
type RunlyticsServer interface {
	BatchUpdate(context.Context, *BatchUpdateRequest) (*BatchUpdateResponse, error)
	mustEmbedUnimplementedRunlyticsServer()
}

// UnimplementedRunlyticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunlyticsServer struct{}

func (UnimplementedRunlyticsServer) BatchUpdate(context.Context, *BatchUpdateRequest) (*BatchUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdate not implemented")
}
func (UnimplementedRunlyticsServer) mustEmbedUnimplementedRunlyticsServer() {}
func (UnimplementedRunlyticsServer) testEmbeddedByValue()                   {}

// UnsafeRunlyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunlyticsServer will
// result in compilation errors.
type UnsafeRunlyticsServer interface {
	mustEmbedUnimplementedRunlyticsServer()
}

func RegisterRunlyticsServer(s grpc.ServiceRegistrar, srv RunlyticsServer) {
	// If the following call pancis, it indicates UnimplementedRunlyticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runlytics_ServiceDesc, srv)
}

func _Runlytics_BatchUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunlyticsServer).BatchUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runlytics_BatchUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunlyticsServer).BatchUpdate(ctx, req.(*BatchUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runlytics_ServiceDesc is the grpc.ServiceDesc for Runlytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runlytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runlytics.Runlytics",
	HandlerType: (*RunlyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchUpdate",
			Handler:    _Runlytics_BatchUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/runlytics.proto",
}
