// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/runlytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []byte                 `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateRequest) Reset() {
	*x = BatchUpdateRequest{}
	mi := &file_proto_runlytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateRequest) ProtoMessage() {}

func (x *BatchUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runlytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_runlytics_proto_rawDescGZIP(), []int{0}
}

func (x *BatchUpdateRequest) GetMetrics() []byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type BatchUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  uint32                 `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateResponse) Reset() {
	*x = BatchUpdateResponse{}
	mi := &file_proto_runlytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateResponse) ProtoMessage() {}

func (x *BatchUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runlytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_runlytics_proto_rawDescGZIP(), []int{1}
}

func (x *BatchUpdateResponse) GetUpdatedCount() uint32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

var File_proto_runlytics_proto protoreflect.FileDescriptor

const file_proto_runlytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/runlytics.proto\x12\trunlytics\".\n" +
	"\x12BatchUpdateRequest\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\fR\ametrics\":\n" +
	"\x13BatchUpdateResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\rR\fupdatedCount2[\n" +
	"\tRunlytics\x12N\n" +
	"\vBatchUpdate\x12\x1d.runlytics.BatchUpdateRequest\x1a\x1e.runlytics.BatchUpdateResponse\"\x00B#Z!github.com/niksmo/runlytics/protob\x06proto3"

var (
	file_proto_runlytics_proto_rawDescOnce sync.Once
	file_proto_runlytics_proto_rawDescData []byte
)

func file_proto_runlytics_proto_rawDescGZIP() []byte {
	file_proto_runlytics_proto_rawDescOnce.Do(func() {
		file_proto_runlytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runlytics_proto_rawDesc), len(file_proto_runlytics_proto_rawDesc)))
	})
	return file_proto_runlytics_proto_rawDescData
}

var file_proto_runlytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_runlytics_proto_goTypes = []any{
	(*BatchUpdateRequest)(nil),  // 0: runlytics.BatchUpdateRequest
	(*BatchUpdateResponse)(nil), // 1: runlytics.BatchUpdateResponse
}
var file_proto_runlytics_proto_depIdxs = []int32{
	0, // 0: runlytics.Runlytics.BatchUpdate:input_type -> runlytics.BatchUpdateRequest
	1, // 1: runlytics.Runlytics.BatchUpdate:output_type -> runlytics.BatchUpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_runlytics_proto_init() }
func file_proto_runlytics_proto_init() {
	if File_proto_runlytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runlytics_proto_rawDesc), len(file_proto_runlytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runlytics_proto_goTypes,
		DependencyIndexes: file_proto_runlytics_proto_depIdxs,
		MessageInfos:      file_proto_runlytics_proto_msgTypes,
	}.Build()
	File_proto_runlytics_proto = out.File
	file_proto_runlytics_proto_goTypes = nil
	file_proto_runlytics_proto_depIdxs = nil
}
